version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/postgresql/data

  moodle:
    build: .
    restart: always
    ports:
      - "8000:80"
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBHOST: db
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_DBNAME: moodle
    depends_on:
      - db

volumes:
  db_data:
